export const CharacterData = {
  monk: {
    sprite: {
      key: 'monk',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 180,
      runSpeed: 300,
      jumpPower: 280,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'instant',
        icon: 'assets/skills/monk/attack.png',
        hitboxSequence: [
          {
            hitbox: {
              width: 50,
              height: 50,
              offsetX: 70,
              offsetY: 70,
              duration: 200,
              effect: 'monk_circle_turn_in',
            },
            damage: 12,
          },
        ],
        animation: 'attack',
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        hitboxSequence: [
          {
            delay: 0,
            hitbox: {
              width: 165,
              height: 75,
              offsetX: 0,
              offsetY: 50,
              duration: 300,
            },
            damage: 10,
          },
        ],
        animation: 'air_attack',
        knockback: { x: 50, y: -150 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
      },
      q_skill: {
        type: 'instant',
        icon: 'assets/skills/monk/q_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: {
              width: 75,
              height: 75,
              offsetX: 90,
              offsetY: 60,
              duration: 300,
            },
            damage: 10,
          },
          {
            delay: 300,
            hitbox: {
              width: 85,
              height: 85,
              offsetX: 90,
              offsetY: 60,
              duration: 300,
            },
            damage: 10,
          },
        ],
        animation: 'q_skill',
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 500,
        cost: { mana: 15 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT_ULTIMATE',
        impactEffect: ['monk_q_skill'],
      },
      w_skill: {
        type: 'instant',
        icon: 'assets/skills/monk/w_skill.png',
        hitboxSequence: [
          {
            delay: 300,
            hitbox: {
              width: 120,
              height: 90,
              offsetX: 130,
              offsetY: 80,
              duration: 300,
            },
            damage: 20,
          },
        ],
        animation: 'w_skill',
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 3000,
        cost: { mana: 25 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT_ULTIMATE',
        impactEffect: ['monk_w_skill'],
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/monk/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/monk/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold',
          maxDuration: 3000,
          manaPerTick: 0,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 3,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/monk/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: {
              width: 175,
              height: 40,
              offsetX: 80,
              offsetY: 100,
              duration: 900,
            },
            damage: 10,
          },
          {
            delay: 700,
            hitbox: {
              width: 55,
              height: 120,
              offsetX: 80,
              offsetY: 60,
              duration: 600,
            },
            damage: 10,
          },
          {
            delay: 1300,
            hitbox: {
              width: 75,
              height: 120,
              offsetX: 80,
              offsetY: 60,
              duration: 600,
            },
            damage: 10,
          },
        ],
        animation: 'r_skill',
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 6000,
        cost: { mana: 50 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT_ULTIMATE',
        impactEffect: [],
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 5 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 26, end: 31 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 26, end: 31 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 51, end: 52 }, frameRate: 4, repeat: 0 },
      { key: 'jump_down', frames: { start: 76, end: 77 }, frameRate: 4, repeat: 0 },
      { key: 'air_attack', frames: { start: 101, end: 106 }, frameRate: 12, repeat: 0 },
      { key: 'attack', frames: { start: 126, end: 130 }, frameRate: 8, repeat: 0 },
      { key: 'q_skill', frames: { start: 155, end: 161 }, frameRate: 8, repeat: 0 },
      { key: 'w_skill', frames: { start: 187, end: 197 }, frameRate: 12, repeat: 0 },
      { key: 'r_skill', frames: { start: 201, end: 230 }, frameRate: 12, repeat: 0 },
      { key: 'e_skill', frames: { start: 226, end: 240 }, frameRate: 8, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 232, end: 238 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 251, end: 255 }, frameRate: 10, repeat: 0 },
      { key: 'take_hit', frames: { start: 301, end: 306 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 326, end: 340 }, frameRate: 15, repeat: 0 },
    ],
  },

  assassin: {
    sprite: {
      key: 'assassin',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 280,
      runSpeed: 450,
      jumpPower: 350,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'instant',
        icon: 'assets/skills/assassin/attack.png',
        animation: 'attack',
        hitboxSequence: [
          {
            delay: 150,
            hitbox: {
              width: 120,
              height: 120,
              offsetX: 90,
              offsetY: 60,
              duration: 300,
              effect: 'assassin_multiple_rectangle',
            },
            damage: 18,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      q_skill: {
        type: 'instant',
        icon: 'assets/skills/assassin/q_skill.png',
        hitboxSequence: [
          {
            delay: 150,
            hitbox: {
              width: 80,
              height: 100,
              offsetX: 60,
              offsetY: 70,
              duration: 800,
            },
            damage: 20,
          },
          {
            delay: 150,
            hitbox: {
              width: 80,
              height: 130,
              offsetX: 150,
              offsetY: 70,
              duration: 800,
            },
            damage: 20,
          },
        ],
        animation: 'q_skill',
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 500,
        cost: { mana: 15 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: ['assassin_q_skill'],
      },
      w_skill: {
        type: 'instant',
        icon: 'assets/skills/assassin/w_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 45, height: 120, offsetX: 0, offsetY: 100 },
            damage: 10,
            movement: { distanceX: 200, distanceY: 0, duration: 550 },
          },
        ],
        animation: 'w_skill',
        knockback: { x: 100, y: -100 },
        effects: ['stun'],
        cooldown: 3000,
        cost: { mana: 25 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: ['assassin_thin_pattern_turn_in'],
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/assassin/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold',
          maxDuration: 3000,
          manaPerTick: 0,
        },
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        effects: ['heal', 'mana_regen', 'defend'],
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/assassin/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 140, height: 120, offsetX: 0, offsetY: 64, duration: 1600 },
            damage: 8,
          },
          {
            delay: 100,
            hitbox: { width: 80, height: 120, offsetX: 0, offsetY: 64, duration: 400 },
            damage: 8,
            movement: { distanceX: 100, distanceY: 0, duration: 200 },
          },
          {
            delay: 300,
            hitbox: { width: 80, height: 120, offsetX: 0, offsetY: -40, duration: 400 },
            damage: 8,
            movement: { distanceX: 0, distanceY: 64, duration: 200 },
          },
          {
            delay: 500,
            hitbox: { width: 80, height: 120, offsetX: -100, offsetY: 64, duration: 400 },
            damage: 8,
            movement: { distanceX: 200, distanceY: 0, duration: 300 },
          },
          {
            delay: 700,
            hitbox: { width: 80, height: 120, offsetX: 100, offsetY: 64, duration: 400 },
            damage: 8,
            movement: { distanceX: -200, distanceY: 0, duration: 300 },
          },
          {
            delay: 900,
            hitbox: { width: 80, height: 120, offsetX: -100, offsetY: 64, duration: 400 },
            damage: 8,
            movement: { distanceX: 200, distanceY: 0, duration: 300 },
          },
        ],
        animation: 'r_skill',
        hitstop: 'FIREKNIGHT_ULTIMATE',
        knockback: { x: 150, y: -50 },
        cooldown: 6000,
        cost: { mana: 50 },
        targetType: 'multi',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/assassin/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 250,
        cooldown: 3000,
        targetType: 'single',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 7 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 30, end: 37 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 30, end: 37 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 60, end: 62 }, frameRate: 3, repeat: 0 },
      { key: 'jump_down', frames: { start: 90, end: 92 }, frameRate: 3, repeat: 0 },
      { key: 'air_attack', frames: { start: 120, end: 126 }, frameRate: 12, repeat: 0 },
      { key: 's_skill', frames: { start: 150, end: 155 }, frameRate: 10, repeat: 0 },
      { key: 'attack', frames: { start: 180, end: 187 }, frameRate: 12, repeat: 0 },
      { key: 'q_skill', frames: { start: 215, end: 227 }, frameRate: 8, repeat: 0 },
      { key: 'w_skill', frames: { start: 253, end: 265 }, frameRate: 12, repeat: 0 },
      { key: 'r_skill', frames: { start: 270, end: 307 }, frameRate: 16, repeat: 0 },
      { key: 'e_skill', frames: { start: 300, end: 307 }, frameRate: 8, repeat: 0 },
      { key: 'e_skill_channeling', frames: { start: 302, end: 304 }, frameRate: 2, repeat: -1 },
      { key: 'defend', frames: { start: 300, end: 307 }, frameRate: 15, repeat: -1 },
      { key: 'take_hit', frames: { start: 330, end: 335 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 360, end: 378 }, frameRate: 15, repeat: 0 },
    ],
  },

  bladekeeper: {
    sprite: {
      key: 'bladekeeper',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 220,
      runSpeed: 380,
      jumpPower: 420,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'instant',
        icon: 'assets/skills/bladekeeper/attack.png',
        animation: 'attack',
        hitboxSequence: [
          {
            delay: 150,
            hitbox: {
              width: 84,
              height: 64,
              offsetX: 70,
              offsetY: 60,
              duration: 300,
              effect: 'bladekeeper_arrow_circle',
            },
            damage: 8,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        animation: 'air_attack',
        hitboxSequence: [
          {
            delay: 150,
            hitbox: {
              width: 104,
              height: 64,
              offsetX: 70,
              offsetY: 60,
              duration: 700,
              effect: 'bladekeeper_arrow_circle',
            },
            damage: 5,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      q_skill: {
        type: 'melee',
        icon: 'assets/skills/bladekeeper/q_skill.png',
        animation: 'q_skill',
        hitboxSequence: [
          {
            delay: 150,
            hitbox: {
              width: 145,
              height: 130,
              offsetX: 90,
              offsetY: 60,
              duration: 700,
            },
            damage: 10,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 500,
        cost: { mana: 15 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: ['bladekeeper_blade_turn_in'],
      },
      w_skill: {
        type: 'melee',
        icon: 'assets/skills/bladekeeper/w_skill.png',
        animation: 'w_skill',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: {
              width: 100,
              height: 80,
              offsetX: 70,
              offsetY: 60,
              duration: 100,
              effect: '',
            },
            damage: 5,
          },
          {
            delay: 100,
            hitbox: {
              width: 110,
              height: 80,
              offsetX: 60,
              offsetY: 70,
              duration: 200,
              effect: '',
            },
            damage: 5,
          },
          {
            delay: 200,
            hitbox: {
              width: 100,
              height: 80,
              offsetX: 70,
              offsetY: 60,
              duration: 100,
              effect: '',
            },
            damage: 5,
          },
          {
            delay: 300,
            hitbox: {
              width: 120,
              height: 80,
              offsetX: 80,
              offsetY: 70,
              duration: 400,
              effect: '',
            },
            damage: 5,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 3000,
        cost: { mana: 25 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/bladekeeper/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/bladekeeper/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold',
          maxDuration: 3000,
          manaPerTick: 0,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/bladekeeper/r_skill.png',
        animation: 'r_skill',
        hitboxSequence: [
          {
            delay: 150,
            hitbox: {
              width: 380,
              height: 110,
              offsetX: 30,
              offsetY: 60,
              duration: 600,
              effect: '',
            },
            damage: 40,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 6000,
        cost: { mana: 50 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT_ULTIMATE',
        impactEffect: ['bladekeeper_r_skill'],
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 7 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 20, end: 27 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 20, end: 27 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 40, end: 42 }, frameRate: 4, repeat: 0 },
      { key: 'jump_down', frames: { start: 60, end: 62 }, frameRate: 4, repeat: 0 },
      { key: 'air_attack', frames: { start: 101, end: 107 }, frameRate: 8, repeat: 0 },
      { key: 'attack', frames: { start: 180, end: 185 }, frameRate: 15, repeat: 0 },
      { key: 'q_skill', frames: { start: 204, end: 207 }, frameRate: 9, repeat: 0 },
      { key: 'w_skill', frames: { start: 227, end: 237 }, frameRate: 20, repeat: 0 },
      { key: 'r_skill', frames: { start: 240, end: 250 }, frameRate: 12, repeat: 0 },
      { key: 'e_skill', frames: { start: 260, end: 271 }, frameRate: 20, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 266, end: 268 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 120, end: 126 }, frameRate: 10, repeat: 0 },
      { key: 'take_hit', frames: { start: 280, end: 285 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 300, end: 311 }, frameRate: 15, repeat: 0 },
    ],
  },

  fireknight: {
    sprite: {
      key: 'fireknight',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 130,
      runSpeed: 220,
      jumpPower: 250,
      maxJumps: 1,
    },
    combat: {
      attackHitbox: { width: 150, height: 155, offsetX: 35, offsetY: 70, duration: 100 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 10,
        icon: 'assets/skills/fireknight/attack.png',
        hitboxSequence: [
          {
            delay: 300,
            hitbox: {
              width: 150,
              height: 150,
              offsetX: 70,
              offsetY: 40,
              effect: 'slash_basic',
              duration: 300,
              damage: 35,
            },
          },
        ],
        hitstop: 'FIREKNIGHT',
        animation: 'attack',
        knockback: { x: 20, y: 50 },
        targetType: 'multi',
        impactEffect: 'fire_knight_slash',
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitboxSequence: [
          {
            delay: 100,
            hitbox: { width: 80, height: 40, offsetX: 0, offsetY: 50, effect: '' },
            movement: { velocityX: 400, velocityY: 0 },
            damage: 10,
          },
        ],
        hitstop: 'FIREKNIGHT',
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      q_skill: {
        type: 'instant',
        damage: 15,
        icon: 'assets/skills/fireknight/q_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 250, height: 140, offsetX: 0, offsetY: 50, effect: '' },
            damage: 10,
            duration: 200,
          },
          {
            delay: 200,
            hitbox: { width: 250, height: 140, offsetX: 0, offsetY: 50, effect: '' },
            damage: 10,
            duration: 200,
          },
          {
            delay: 400,
            hitbox: { width: 250, height: 140, offsetX: 0, offsetY: 50, effect: '' },
            damage: 10,
            duration: 200,
          },
          {
            delay: 600,
            hitbox: { width: 250, height: 140, offsetX: 0, offsetY: 50, effect: '' },
            damage: 10,
            duration: 200,
          },
          {
            delay: 800,
            hitbox: { width: 250, height: 140, offsetX: 0, offsetY: 50, effect: '' },
            damage: 20,
            duration: 200,
          },
        ],
        hitstop: 'FIREKNIGHT',
        animation: 'q_skill',
        knockback: { x: 50, y: -50 },
        cooldown: 500,
        cost: { mana: 15 },
        targetType: 'multi',
        impactEffect: ['fire_knight_q_skill', 'fire_knight_q_skill_flip'],
      },
      w_skill: {
        type: 'instant',
        damage: 25,
        icon: 'assets/skills/fireknight/w_skill.png',
        hitboxSequence: [
          {
            delay: 100,
            hitbox: {
              width: 120,
              height: 40,
              offsetX: -30,
              offsetY: 120,
              effect: '',
              duration: 200,
            },
            damage: 20,
          },
          {
            delay: 300,
            hitbox: { width: 40, height: 155, offsetX: 40, offsetY: 60, effect: '', duration: 200 },
            damage: 20,
          },
          {
            delay: 500,
            hitbox: {
              width: 150,
              height: 130,
              offsetX: 130,
              offsetY: 60,
              effect: '',
              duration: 300,
            },
            damage: 40,
          },
        ],
        hitstop: 'FIREKNIGHT',
        animation: 'w_skill',
        knockback: { x: 100, y: -100 },
        effects: ['stun'],
        cooldown: 3000,
        cost: { mana: 25 },
        targetType: 'multi',
        impactEffect: ['fire_knight_w_skill'],
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/fireknight/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/fireknight/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold',
          maxDuration: 3000,
          manaPerTick: 0,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/fireknight/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: {
              width: 175,
              height: 40,
              offsetX: 80,
              offsetY: 20,
              duration: 700,
            },
            damage: 20,
          },
          {
            delay: 700,
            hitbox: {
              width: 100,
              height: 90,
              offsetX: -30,
              offsetY: 80,
              duration: 500,
            },
            damage: 30,
          },
          {
            delay: 1000,
            hitbox: {
              width: 220,
              height: 150,
              offsetX: 100,
              offsetY: 50,
              duration: 500,
            },
            damage: 50,
          },
        ],
        animation: 'r_skill',
        knockback: { x: 30, y: 30 },
        effects: ['burn'],
        cooldown: 6000,
        cost: { mana: 50 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT_ULTIMATE',
        impactEffect: ['fire_knight_r_skill_ready', 'fire_knight_r_skill'],
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 7 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 28, end: 35 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 28, end: 35 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 56, end: 58 }, frameRate: 2, repeat: 0 },
      { key: 'jump_down', frames: { start: 84, end: 86 }, frameRate: 2, repeat: 0 },
      { key: 'air_attack', frames: { start: 140, end: 147 }, frameRate: 12, repeat: 0 },
      { key: 'attack', frames: { start: 196, end: 206 }, frameRate: 10, repeat: 0 },
      { key: 'q_skill', frames: { start: 231, end: 242 }, frameRate: 13, repeat: 0 },
      { key: 'w_skill', frames: { start: 270, end: 279 }, frameRate: 12, repeat: 0 },
      { key: 'r_skill', frames: { start: 280, end: 297 }, frameRate: 10, repeat: 0 },
      { key: 'e_skill', frames: { start: 308, end: 317 }, frameRate: 8, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 310, end: 315 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 168, end: 175 }, frameRate: 14, repeat: 0 },
      { key: 'take_hit', frames: { start: 338, end: 343 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 366, end: 378 }, frameRate: 15, repeat: 0 },
    ],
  },

  ranger: {
    sprite: {
      key: 'ranger',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        icon: 'assets/skills/ranger/attack.png',
        animation: 'attack',
        hitboxSequence: [
          {
            delay: 150,
            hitbox: {
              width: 120,
              height: 120,
              offsetX: 90,
              offsetY: 60,
              duration: 300,
              effect: 'assassin_multiple_rectangle',
            },
            damage: 30,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      q_skill: {
        type: 'melee',
        damage: 15,
        icon: 'assets/skills/ranger/q_skill.png',
        hitbox: { width: 90, height: 40, offsetX: 30, offsetY: 70 },
        animation: 'q_skill',
        knockback: { x: 150, y: -50 },
        cooldown: 2000,
        cost: { mana: 50 },
        targetType: 'multi',
      },
      w_skill: {
        type: 'melee',
        damage: 25,
        icon: 'assets/skills/ranger/w_skill.png',
        hitbox: [
          { width: 175, height: 40, offsetX: 80, offsetY: 100 },
          { width: 70, height: 90, offsetX: 130, offsetY: 60 },
        ],
        animation: 'w_skill',
        knockback: { x: 100, y: -100 },
        effects: ['stun'],
        cooldown: 500,
        cost: { mana: 15 },
        targetType: 'multi',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/ranger/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/ranger/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold',
          maxDuration: 3000,
          manaPerTick: 0,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/ranger/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        animation: 'r_skill',
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 6000,
        cost: { mana: 50 },
        targetType: 'multi',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 11 }, frameRate: 12, repeat: -1 },
      { key: 'walk', frames: { start: 22, end: 31 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 22, end: 31 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 88, end: 96 }, frameRate: 9, repeat: 0 },
      { key: 'jump_down', frames: { start: 97, end: 109 }, frameRate: 13, repeat: 0 },
      { key: 'air_attack', frames: { start: 154, end: 163 }, frameRate: 12, repeat: 0 },
      { key: 'attack', frames: { start: 242, end: 256 }, frameRate: 15, repeat: 0 },
      { key: 'q_skill', frames: { start: 242, end: 256 }, frameRate: 15, repeat: 0 },
      { key: 'w_skill', frames: { start: 264, end: 275 }, frameRate: 12, repeat: 0 },
      { key: 'r_skill', frames: { start: 201, end: 230 }, frameRate: 30, repeat: 0 },
      { key: 'e_skill', frames: { start: 226, end: 240 }, frameRate: 8, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 232, end: 238 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 176, end: 183 }, frameRate: 15, repeat: 0 },
      { key: 'take_hit', frames: { start: 301, end: 306 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 326, end: 340 }, frameRate: 15, repeat: 0 },
    ],
  },

  mauler: {
    sprite: {
      key: 'mauler',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 180,
      runSpeed: 400,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        icon: 'assets/skills/mauler/attack.png',
        animation: 'attack',
        hitboxSequence: [
          {
            delay: 150,
            hitbox: {
              width: 120,
              height: 120,
              offsetX: 90,
              offsetY: 60,
              duration: 300,
              effect: 'mauler_rectangle_shield',
            },
            damage: 25,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        animation: 'air_attack',
        hitboxSequence: [
          {
            delay: 150,
            hitbox: {
              width: 120,
              height: 120,
              offsetX: 90,
              offsetY: 60,
              duration: 300,
              effect: 'mauler_rectangle_shield',
            },
            damage: 25,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      q_skill: {
        type: 'melee',
        icon: 'assets/skills/mauler/q_skill.png',
        animation: 'q_skill',
        hitboxSequence: [
          {
            delay: 100,
            hitbox: {
              width: 100,
              height: 100,
              offsetX: 40,
              offsetY: 10,
              duration: 500,
              effect: '',
            },
            damage: 30,
            movement: { distanceX: 60, distanceY: 60, duration: 550 },
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 500,
        cost: { mana: 15 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: ['mauler_q_skill'],
      },
      w_skill: {
        type: 'instant',
        icon: 'assets/skills/mauler/w_skill.png',
        animation: 'w_skill',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: {
              width: 180,
              height: 40,
              offsetX: 40,
              offsetY: 100,
              duration: 600,
              effect: '',
            },
            damage: 10,
            movement: { distanceX: 140, distanceY: 0, duration: 300 },
          },
          {
            delay: 500,
            hitbox: {
              width: 130,
              height: 130,
              offsetX: 200,
              offsetY: 100,
              duration: 300,
              effect: '',
            },
            damage: 10,
            movement: { distanceX: 0, distanceY: -100, duration: 100 },
          },
        ],
        knockback: { x: 100, y: -150 },
        effects: ['burn'],
        cooldown: 3000,
        cost: { mana: 25 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: ['mauler_w_skill'],
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/mauler/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 200,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/mauler/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold',
          maxDuration: 3000,
          manaPerTick: 0,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/mauler/r_skill.png',
        animation: 'r_skill',
        hitboxSequence: [
          {
            delay: 600,
            hitbox: {
              width: 290,
              height: 160,
              offsetX: 130,
              offsetY: 160,
              duration: 500,
              effect: '',
            },
            damage: 40,
            movement: { distanceX: 0, distanceY: -100, duration: 200 },
          },
          {
            delay: 600,
            hitbox: {
              width: 50,
              height: 50,
              offsetX: 130,
              offsetY: 30,
              duration: 500,
              effect: '',
            },
            damage: 20,
          },
          {
            delay: 600,
            hitbox: {
              width: 50,
              height: 50,
              offsetX: 90,
              offsetY: 90,
              duration: 500,
              effect: '',
            },
            damage: 20,
          },
          {
            delay: 600,
            hitbox: {
              width: 50,
              height: 50,
              offsetX: 180,
              offsetY: 70,
              duration: 500,
              effect: '',
            },
            damage: 20,
          },
          {
            delay: 600,
            hitbox: {
              width: 50,
              height: 50,
              offsetX: 230,
              offsetY: 80,
              duration: 500,
              effect: '',
            },
            damage: 20,
          },
        ],
        knockback: { x: 100, y: -150 },
        effects: ['burn'],
        cooldown: 6000,
        cost: { mana: 50 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 7 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 21, end: 28 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 21, end: 28 }, frameRate: 16, repeat: -1 },
      { key: 'jump', frames: { start: 42, end: 44 }, frameRate: 3, repeat: 0 },
      { key: 'jump_down', frames: { start: 63, end: 65 }, frameRate: 3, repeat: 0 },
      { key: 'air_attack', frames: { start: 105, end: 112 }, frameRate: 8, repeat: 0 },
      { key: 'attack', frames: { start: 147, end: 153 }, frameRate: 14, repeat: 0 },
      { key: 'q_skill', frames: { start: 168, end: 174 }, frameRate: 14, repeat: 0 },
      { key: 'w_skill', frames: { start: 189, end: 205 }, frameRate: 16, repeat: 0 },
      { key: 'r_skill', frames: { start: 210, end: 224 }, frameRate: 12, repeat: 0 },
      { key: 'e_skill', frames: { start: 231, end: 239 }, frameRate: 8, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 233, end: 235 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 126, end: 133 }, frameRate: 10, repeat: 0 },
      { key: 'take_hit', frames: { start: 252, end: 257 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 273, end: 187 }, frameRate: 15, repeat: 0 },
    ],
  },

  princess: {
    sprite: {
      key: 'princess',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 210,
      runSpeed: 340,
      jumpPower: 380,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'instant',
        icon: 'assets/skills/princess/attack.png',
        animation: 'attack',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: {
              width: 120,
              height: 40,
              offsetX: 50,
              offsetY: 75,
              duration: 300,
              effect: '',
            },
            damage: 8,
          },
          {
            delay: 300,
            hitbox: {
              width: 120,
              height: 40,
              offsetX: 90,
              offsetY: 75,
              duration: 500,
              effect: 'princess_water_four_circles_turn_in',
            },
            damage: 12,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      air_attack: {
        type: 'melee',
        animation: 'air_attack',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: {
              width: 120,
              height: 40,
              offsetX: 50,
              offsetY: 75,
              duration: 300,
              effect: '',
            },
            damage: 5,
          },
          {
            delay: 200,
            hitbox: {
              width: 120,
              height: 60,
              offsetX: 100,
              offsetY: 55,
              duration: 500,
              effect: 'princess_water_four_circles_turn_in',
            },
            damage: 5,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      q_skill: {
        type: 'melee',
        icon: 'assets/skills/princess/q_skill.png',
        animation: 'q_skill',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: {
              width: 90,
              height: 90,
              offsetX: 0,
              offsetY: 60,
              duration: 600,
              effect: '',
            },
            damage: 5,
          },
          {
            delay: 600,
            hitbox: {
              width: 120,
              height: 40,
              offsetX: 90,
              offsetY: 75,
              duration: 500,
              effect: '',
            },
            damage: 10,
          },
          {
            delay: 700,
            hitbox: {
              width: 70,
              height: 70,
              offsetX: 140,
              offsetY: 75,
              duration: 500,
              effect: '',
            },
            damage: 15,
          },
        ],
        knockback: { x: 50, y: -150 },
        effects: ['burn'],
        cooldown: 500,
        cost: { mana: 15 },
        targetType: 'multi',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      w_skill: {
        type: 'melee',
        damage: 25,
        icon: 'assets/skills/princess/w_skill.png',
        hitboxSequence: [
          {
            delay: 100,
            hitbox: {
              width: 180,
              height: 40,
              offsetX: 80,
              offsetY: 100,
              duration: 300,
              effect: 'energy_wave',
            },
            damage: 20,
          },
          {
            delay: 200,
            hitbox: {
              width: 120,
              height: 90,
              offsetX: 140,
              offsetY: 60,
              duration: 400,
              effect: 'impact_heavy',
            },
            damage: 30,
          },
        ],
        hitstop: 'FIREKNIGHT',
        animation: 'w_skill',
        knockback: { x: 100, y: -100 },
        effects: ['stun'],
        cooldown: 3000,
        cost: { mana: 25 },
        targetType: 'multi',
        impactEffect: 'explosion',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/princess/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 250,
        cooldown: 3000,
        targetType: 'single',
        dashEffect: 'dash_trail',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/princess/e_skill.png',
        hitstop: 'BOSS_ULTIMATE',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold',
          maxDuration: 3000,
          manaPerTick: 0,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
        healEffect: 'heal_aura',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/princess/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: {
              width: 175,
              height: 130,
              offsetX: 110,
              offsetY: 200,
              effect: 'sword_beam',
              duration: 600,
            },
            damage: 10,
            movement: { distanceX: 0, distanceY: -150, duration: 250 },
          },
          {
            delay: 600,
            hitbox: {
              width: 85,
              height: 90,
              offsetX: 110,
              offsetY: 0,
              effect: 'sword_beam',
              duration: 600,
            },
            damage: 10,
            movement: { distanceX: 0, distanceY: 150, duration: 350 },
          },
          {
            delay: 1200,
            hitbox: {
              width: 160,
              height: 90,
              offsetX: 110,
              offsetY: 0,
              effect: 'sword_beam',
              duration: 600,
            },
            damage: 10,
            movement: { distanceX: 0, distanceY: 150, duration: 350 },
          },
        ],
        hitstop: 'FIREKNIGHT_ULTIMATE',
        animation: 'r_skill',
        knockback: { x: 30, y: -150 },
        effects: ['burn'],
        cooldown: 6000,
        cost: { mana: 50 },
        targetType: 'multi',
        impactEffect: 'princess_r_skill',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 7 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 32, end: 41 }, frameRate: 10, repeat: -1 },
      { key: 'run', frames: { start: 64, end: 71 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 96, end: 98 }, frameRate: 4, repeat: 0 },
      { key: 'jump_down', frames: { start: 128, end: 130 }, frameRate: 4, repeat: 0 },
      { key: 'air_attack', frames: { start: 162, end: 167 }, frameRate: 12, repeat: 0 },
      { key: 'attack', frames: { start: 224, end: 230 }, frameRate: 7, repeat: 0 },
      { key: 'q_skill', frames: { start: 260, end: 276 }, frameRate: 15, repeat: 0 },
      { key: 'w_skill', frames: { start: 304, end: 314 }, frameRate: 12, repeat: 0 },
      { key: 'r_skill', frames: { start: 321, end: 351 }, frameRate: 15, repeat: 0 },
      { key: 'e_skill', frames: { start: 352, end: 363 }, frameRate: 8, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 354, end: 360 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 192, end: 197 }, frameRate: 10, repeat: 0 },
      { key: 'take_hit', frames: { start: 384, end: 390 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 416, end: 436 }, frameRate: 21, repeat: 0 },
    ],
  },

  soul: {
    sprite: {
      key: 'soul',
      frameWidth: 32,
      frameHeight: 32,
      scale: 2.0,
    },
    base: {
      x: 200,
      y: 600,
    },
    physics: {
      collisionBox: { width: 32, height: 64, offsetX: 16, offsetY: 0 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 35, offsetX: 35, offsetY: 0, duration: 400 },
      comboWindow: 400,
    },
    skills: {
      attack: {
        type: 'melee',
        icon: 'assets/skills/soul/attack.png',
        animation: 'attack',
        hitboxSequence: [
          {
            delay: 150,
            hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 0, duration: 100 },
            damage: 10,
          },
        ],
        knockback: { x: 50, y: 50 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'single',
        hitstop: 'FIREKNIGHT',
        impactEffect: [''],
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/soul/dash.png',
        distance: 200,
        speed: 600,
        animation: 'run',
        invincible: true,
        cooldown: 2000,
        targetType: 'single',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 1 }, frameRate: 3, repeat: -1 },
      { key: 'walk', frames: { start: 25, end: 32 }, frameRate: 6, repeat: -1 },
      { key: 'run', frames: { start: 25, end: 32 }, frameRate: 10, repeat: -1 },
      { key: 'jump', frames: { start: 41, end: 48 }, frameRate: 8, repeat: 0 },
      { key: 'jump_down', frames: { start: 41, end: 48 }, frameRate: 8, repeat: 0 },
      { key: 'attack', frames: { start: 65, end: 68 }, frameRate: 12, repeat: 0 },
      { key: 'death', frames: { start: 56, end: 63 }, frameRate: 12, repeat: 0 },
    ],
  },
};
