export const CharacterData = {
  monk: {
    sprite: {
      key: 'monk',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 10,
        icon: 'assets/skills/monk/attack.png', // 아이콘 추가
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      q_skill: {
        type: 'melee',
        damage: 15,
        icon: 'assets/skills/monk/q_skill.png',
        hitbox: { width: 90, height: 40, offsetX: 30, offsetY: 70 },
        animation: 'q_skill',
        knockback: { x: 150, y: -50 },
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      w_skill: {
        type: 'melee',
        damage: 25,
        icon: 'assets/skills/monk/w_skill.png',
        hitbox: [
          { width: 175, height: 40, offsetX: 80, offsetY: 100 },
          { width: 70, height: 90, offsetX: 130, offsetY: 60 },
        ],
        hitboxDelay: 300,
        animation: 'w_skill',
        knockback: { x: 200, y: -100 },
        effects: ['stun'],
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/monk/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/monk/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold', // 'hold' = 키를 누르고 있는 동안 유지
          maxDuration: 3000, // 최대 3초
          manaPerTick: 0, // 100ms당 2 마나 소모,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/monk/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        animation: 'r_skill',
        knockback: { x: 250, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 5 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 26, end: 31 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 26, end: 31 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 51, end: 52 }, frameRate: 4, repeat: 0 },
      { key: 'jump_down', frames: { start: 76, end: 77 }, frameRate: 4, repeat: 0 },
      { key: 'air_attack', frames: { start: 101, end: 106 }, frameRate: 12, repeat: 0 },
      { key: 'attack', frames: { start: 126, end: 130 }, frameRate: 6, repeat: 0 },
      { key: 'q_skill', frames: { start: 155, end: 161 }, frameRate: 8, repeat: 0 },
      { key: 'w_skill', frames: { start: 187, end: 197 }, frameRate: 12, repeat: 0 },
      { key: 'r_skill', frames: { start: 201, end: 230 }, frameRate: 30, repeat: 0 },
      { key: 'e_skill', frames: { start: 226, end: 240 }, frameRate: 8, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 232, end: 238 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 251, end: 255 }, frameRate: 10, repeat: 0 },
      // { key: 'e_skill', frames: { start: 276, end: 290 }, frameRate: 15, repeat: -1 },
      { key: 'take_hit', frames: { start: 301, end: 306 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 326, end: 340 }, frameRate: 15, repeat: 0 },
    ],
  },

  assassin: {
    sprite: {
      key: 'assassin',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 10,
        icon: 'assets/skills/assassin/attack.png',
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'attack',
        knockback: { x: 100, y: 0 },
        cooldown: 0,
        targetType: 'multi',
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      q_skill: {
        type: 'melee',
        damage: 15,
        icon: 'assets/skills/assassin/q_skill.png',
        hitbox: { width: 90, height: 40, offsetX: 30, offsetY: 70 },
        animation: 'q_skill',
        knockback: { x: 150, y: -50 },
        cooldown: 1000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      w_skill: {
        type: 'instant',
        icon: 'assets/skills/assassin/w_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        animation: 'w_skill',
        knockback: { x: 200, y: -100 },
        effects: ['stun'],
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/assassin/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold', // 'hold' = 키를 누르고 있는 동안 유지
          maxDuration: 3000, // 최대 3초
          manaPerTick: 0, // 100ms당 2 마나 소모,
        },
        // cost: { mana: 10 },
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        effects: ['heal', 'mana_regen', 'defend'],
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/assassin/r_skill.png',
        hitboxSequence: [
          {
            delay: 100,
            hitbox: { width: 60, height: 40, offsetX: 250, offsetY: 100 },
            damage: 8,
            duration: 800,
            movement: { velocityX: 400, velocityY: 0 },
          },
          {
            delay: 200,
            hitbox: { width: 60, height: 40, offsetX: 50, offsetY: 80 },
            damage: 8,
            duration: 800,
            movement: { velocityX: 400, velocityY: -50 },
          },
          {
            delay: 300,
            hitbox: { width: 60, height: 40, offsetX: -150, offsetY: 120 },
            damage: 8,
            duration: 800,
            movement: { velocityX: 400, velocityY: 50 },
          },
        ],
        animation: 'r_skill',
        knockback: { x: 150, y: -50 },
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/assassin/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 7 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 30, end: 37 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 30, end: 37 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 60, end: 62 }, frameRate: 3, repeat: 0 },
      { key: 'jump_down', frames: { start: 90, end: 92 }, frameRate: 3, repeat: 0 },
      { key: 'air_attack', frames: { start: 120, end: 126 }, frameRate: 12, repeat: 0 },
      { key: 's_skill', frames: { start: 150, end: 155 }, frameRate: 10, repeat: 0 },
      { key: 'attack', frames: { start: 180, end: 187 }, frameRate: 12, repeat: 0 },
      { key: 'q_skill', frames: { start: 215, end: 227 }, frameRate: 8, repeat: 0 },
      { key: 'w_skill', frames: { start: 253, end: 265 }, frameRate: 25, repeat: 0 },
      { key: 'r_skill', frames: { start: 270, end: 307 }, frameRate: 37, repeat: 0 },
      { key: 'e_skill', frames: { start: 300, end: 307 }, frameRate: 8, repeat: 0 },
      { key: 'e_skill_channeling', frames: { start: 302, end: 304 }, frameRate: 2, repeat: -1 },
      { key: 'defend', frames: { start: 300, end: 307 }, frameRate: 15, repeat: -1 },
      { key: 'take_hit', frames: { start: 330, end: 335 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 360, end: 378 }, frameRate: 15, repeat: 0 },
    ],
  },

  bladekeeper: {
    sprite: {
      key: 'bladekeeper',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 400,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 10,
        icon: 'assets/skills/bladekeeper/attack.png', // 아이콘 추가
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      q_skill: {
        type: 'melee',
        damage: 15,
        icon: 'assets/skills/bladekeeper/q_skill.png',
        hitbox: { width: 90, height: 40, offsetX: 30, offsetY: 70 },
        animation: 'q_skill',
        knockback: { x: 150, y: -50 },
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      w_skill: {
        type: 'melee',
        damage: 25,
        icon: 'assets/skills/bladekeeper/w_skill.png',
        hitbox: [
          { width: 175, height: 40, offsetX: 80, offsetY: 100 },
          { width: 70, height: 90, offsetX: 130, offsetY: 60 },
        ],
        hitboxDelay: 300,
        animation: 'w_skill',
        knockback: { x: 200, y: -100 },
        effects: ['stun'],
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/bladekeeper/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/bladekeeper/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold', // 'hold' = 키를 누르고 있는 동안 유지
          maxDuration: 3000, // 최대 3초
          manaPerTick: 0, // 100ms당 2 마나 소모,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/bladekeeper/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        animation: 'r_skill',
        knockback: { x: 250, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 7 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 20, end: 27 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 20, end: 27 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 40, end: 42 }, frameRate: 4, repeat: 0 },
      { key: 'jump_down', frames: { start: 60, end: 62 }, frameRate: 4, repeat: 0 },
      { key: 'air_attack', frames: { start: 101, end: 108 }, frameRate: 7, repeat: 0 },
      { key: 'attack', frames: { start: 180, end: 185 }, frameRate: 15, repeat: 0 },
      // { key: 'q_skill', frames: { start: 160, end: 169 }, frameRate: 9, repeat: 0 },
      { key: 'q_skill', frames: { start: 204, end: 207 }, frameRate: 9, repeat: 0 },
      { key: 'w_skill', frames: { start: 227, end: 237 }, frameRate: 20, repeat: 0 },
      { key: 'r_skill', frames: { start: 240, end: 250 }, frameRate: 30, repeat: 0 },
      { key: 'e_skill', frames: { start: 260, end: 271 }, frameRate: 20, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 266, end: 268 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 120, end: 126 }, frameRate: 10, repeat: 0 },
      // { key: 's_skill', frames: { start: 140, end: 146 }, frameRate: 10, repeat: 0 },
      { key: 'take_hit', frames: { start: 280, end: 285 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 300, end: 311 }, frameRate: 15, repeat: 0 },
    ],
  },

  fireknight: {
    sprite: {
      key: 'fireknight',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 10,
        icon: 'assets/skills/fireknight/attack.png', // 아이콘 추가
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      q_skill: {
        type: 'melee',
        damage: 15,
        icon: 'assets/skills/fireknight/q_skill.png',
        hitbox: { width: 90, height: 40, offsetX: 30, offsetY: 70 },
        animation: 'q_skill',
        knockback: { x: 150, y: -50 },
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      w_skill: {
        type: 'melee',
        damage: 25,
        icon: 'assets/skills/fireknight/w_skill.png',
        hitbox: [
          { width: 175, height: 40, offsetX: 80, offsetY: 100 },
          { width: 70, height: 90, offsetX: 130, offsetY: 60 },
        ],
        hitboxDelay: 300,
        animation: 'w_skill',
        knockback: { x: 200, y: -100 },
        effects: ['stun'],
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/fireknight/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/fireknight/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold', // 'hold' = 키를 누르고 있는 동안 유지
          maxDuration: 3000, // 최대 3초
          manaPerTick: 0, // 100ms당 2 마나 소모,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/fireknight/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        animation: 'r_skill',
        knockback: { x: 250, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 5 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 26, end: 31 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 26, end: 31 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 51, end: 52 }, frameRate: 4, repeat: 0 },
      { key: 'jump_down', frames: { start: 76, end: 77 }, frameRate: 4, repeat: 0 },
      { key: 'air_attack', frames: { start: 101, end: 106 }, frameRate: 12, repeat: 0 },
      { key: 'attack', frames: { start: 126, end: 130 }, frameRate: 6, repeat: 0 },
      { key: 'q_skill', frames: { start: 155, end: 161 }, frameRate: 8, repeat: 0 },
      { key: 'w_skill', frames: { start: 187, end: 197 }, frameRate: 12, repeat: 0 },
      { key: 'r_skill', frames: { start: 201, end: 230 }, frameRate: 30, repeat: 0 },
      { key: 'e_skill', frames: { start: 226, end: 240 }, frameRate: 8, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 232, end: 238 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 251, end: 255 }, frameRate: 10, repeat: 0 },
      // { key: 'e_skill', frames: { start: 276, end: 290 }, frameRate: 15, repeat: -1 },
      { key: 'take_hit', frames: { start: 301, end: 306 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 326, end: 340 }, frameRate: 15, repeat: 0 },
    ],
  },

  ranger: {
    sprite: {
      key: 'ranger',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 10,
        icon: 'assets/skills/ranger/attack.png', // 아이콘 추가
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      q_skill: {
        type: 'melee',
        damage: 15,
        icon: 'assets/skills/ranger/q_skill.png',
        hitbox: { width: 90, height: 40, offsetX: 30, offsetY: 70 },
        animation: 'q_skill',
        knockback: { x: 150, y: -50 },
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      w_skill: {
        type: 'melee',
        damage: 25,
        icon: 'assets/skills/ranger/w_skill.png',
        hitbox: [
          { width: 175, height: 40, offsetX: 80, offsetY: 100 },
          { width: 70, height: 90, offsetX: 130, offsetY: 60 },
        ],
        animation: 'w_skill',
        knockback: { x: 200, y: -100 },
        effects: ['stun'],
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/ranger/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/ranger/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold', // 'hold' = 키를 누르고 있는 동안 유지
          maxDuration: 3000, // 최대 3초
          manaPerTick: 0, // 100ms당 2 마나 소모,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/ranger/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        animation: 'r_skill',
        knockback: { x: 250, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 11 }, frameRate: 12, repeat: -1 },
      { key: 'walk', frames: { start: 22, end: 31 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 22, end: 31 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 88, end: 96 }, frameRate: 9, repeat: 0 },
      { key: 'jump_down', frames: { start: 97, end: 109 }, frameRate: 13, repeat: 0 },
      { key: 'air_attack', frames: { start: 154, end: 163 }, frameRate: 12, repeat: 0 },
      { key: 'attack', frames: { start: 242, end: 256 }, frameRate: 15, repeat: 0 },
      { key: 'q_skill', frames: { start: 242, end: 256 }, frameRate: 15, repeat: 0 },
      { key: 'w_skill', frames: { start: 264, end: 275 }, frameRate: 12, repeat: 0 },
      { key: 'r_skill', frames: { start: 201, end: 230 }, frameRate: 30, repeat: 0 },
      { key: 'e_skill', frames: { start: 226, end: 240 }, frameRate: 8, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 232, end: 238 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 176, end: 183 }, frameRate: 15, repeat: 0 },
      // { key: 's_skill_ground', frames: { start: 198, end: 210 }, frameRate: 15, repeat: 0 }, //slide
      // { key: 'e_skill', frames: { start: 276, end: 290 }, frameRate: 15, repeat: -1 },
      { key: 'take_hit', frames: { start: 301, end: 306 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 326, end: 340 }, frameRate: 15, repeat: 0 },
    ],
  },

  mauler: {
    sprite: {
      key: 'mauler',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 10,
        icon: 'assets/skills/mauler/attack.png', // 아이콘 추가
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      q_skill: {
        type: 'melee',
        damage: 15,
        icon: 'assets/skills/mauler/q_skill.png',
        hitbox: { width: 90, height: 40, offsetX: 30, offsetY: 70 },
        animation: 'q_skill',
        knockback: { x: 150, y: -50 },
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      w_skill: {
        type: 'melee',
        damage: 25,
        icon: 'assets/skills/mauler/w_skill.png',
        hitbox: [
          { width: 175, height: 40, offsetX: 80, offsetY: 100 },
          { width: 70, height: 90, offsetX: 130, offsetY: 60 },
        ],
        hitboxDelay: 300,
        animation: 'w_skill',
        knockback: { x: 200, y: -100 },
        effects: ['stun'],
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/mauler/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/mauler/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold', // 'hold' = 키를 누르고 있는 동안 유지
          maxDuration: 3000, // 최대 3초
          manaPerTick: 0, // 100ms당 2 마나 소모,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/mauler/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        animation: 'r_skill',
        knockback: { x: 250, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 7 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 21, end: 28 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 21, end: 28 }, frameRate: 16, repeat: -1 },
      { key: 'jump', frames: { start: 42, end: 44 }, frameRate: 3, repeat: 0 },
      { key: 'jump_down', frames: { start: 63, end: 65 }, frameRate: 3, repeat: 0 },
      { key: 'air_attack', frames: { start: 105, end: 112 }, frameRate: 8, repeat: 0 },
      { key: 'attack', frames: { start: 147, end: 153 }, frameRate: 14, repeat: 0 },
      { key: 'q_skill', frames: { start: 168, end: 174 }, frameRate: 14, repeat: 0 },
      { key: 'w_skill', frames: { start: 189, end: 205 }, frameRate: 16, repeat: 0 },
      { key: 'r_skill', frames: { start: 210, end: 224 }, frameRate: 12, repeat: 0 },
      { key: 'e_skill', frames: { start: 231, end: 239 }, frameRate: 8, repeat: -1 },
      { key: 'e_skill_channeling', frames: { start: 232, end: 238 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 126, end: 133 }, frameRate: 10, repeat: 0 },
      { key: 'take_hit', frames: { start: 252, end: 257 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 273, end: 187 }, frameRate: 15, repeat: 0 },
    ],
  },

  princess: {
    sprite: {
      key: 'princess',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 10,
        icon: 'assets/skills/princess/attack.png', // 아이콘 추가
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      q_skill: {
        type: 'melee',
        damage: 15,
        icon: 'assets/skills/princess/q_skill.png',
        hitbox: { width: 90, height: 40, offsetX: 30, offsetY: 70 },
        animation: 'q_skill',
        knockback: { x: 150, y: -50 },
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      w_skill: {
        type: 'melee',
        damage: 25,
        icon: 'assets/skills/princess/w_skill.png',
        hitbox: [
          { width: 175, height: 40, offsetX: 80, offsetY: 100 },
          { width: 70, height: 90, offsetX: 130, offsetY: 60 },
        ],
        // hitboxDelay: 300,
        animation: 'w_skill',
        knockback: { x: 200, y: -100 },
        effects: ['stun'],
        cooldown: 2000,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      s_skill: {
        type: 'movement',
        icon: 'assets/skills/princess/s_skill.png',
        animation: 's_skill',
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      e_skill: {
        type: 'channeling',
        icon: 'assets/skills/princess/e_skill.png',
        animation: 'e_skill',
        isChanneling: true,
        channeling: {
          type: 'hold', // 'hold' = 키를 누르고 있는 동안 유지
          maxDuration: 3000, // 최대 3초
          manaPerTick: 0, // 100ms당 2 마나 소모,
        },
        effects: ['heal', 'mana_regen'],
        cooldown: 3000,
        healAmount: 2,
        manaAmount: 2,
        targetType: 'single',
      },
      r_skill: {
        type: 'instant',
        icon: 'assets/skills/princess/r_skill.png',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        animation: 'r_skill',
        knockback: { x: 250, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 7 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 32, end: 41 }, frameRate: 10, repeat: -1 },
      { key: 'run', frames: { start: 64, end: 71 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 96, end: 98 }, frameRate: 4, repeat: 0 },
      { key: 'jump_down', frames: { start: 128, end: 130 }, frameRate: 4, repeat: 0 },
      { key: 'air_attack', frames: { start: 162, end: 167 }, frameRate: 12, repeat: 0 },
      { key: 'attack', frames: { start: 224, end: 230 }, frameRate: 7, repeat: 0 },
      { key: 'q_skill', frames: { start: 260, end: 276 }, frameRate: 15, repeat: 0 },
      { key: 'w_skill', frames: { start: 304, end: 314 }, frameRate: 12, repeat: 0 },
      { key: 'r_skill', frames: { start: 321, end: 351 }, frameRate: 15, repeat: 0 },
      { key: 'e_skill', frames: { start: 352, end: 363 }, frameRate: 8, repeat: -1 },
      // { key: 'e_skill', frames: { start: 384, end: 395 }, frameRate: 8, repeat: -1 }, defend
      { key: 'e_skill_channeling', frames: { start: 354, end: 360 }, frameRate: 8, repeat: -1 },
      { key: 's_skill', frames: { start: 192, end: 197 }, frameRate: 10, repeat: 0 },
      // { key: 'e_skill', frames: { start: 276, end: 290 }, frameRate: 15, repeat: -1 },
      { key: 'take_hit', frames: { start: 384, end: 390 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 416, end: 436 }, frameRate: 21, repeat: 0 },
    ],
  },

  soul: {
    sprite: {
      key: 'soul',
      frameWidth: 32,
      frameHeight: 32,
      scale: 2.0,
    },
    base: {
      x: 200,
      y: 600,
    },
    physics: {
      collisionBox: { width: 32, height: 64, offsetX: 16, offsetY: 0 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 35, offsetX: 35, offsetY: 0, duration: 400 },
      comboWindow: 400,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 15,
        icon: 'assets/skills/soul/attack.png',
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 0 },
        animation: 'attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      air_attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        animation: 'air_attack',
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      dash: {
        type: 'movement',
        icon: 'assets/skills/soul/dash.png',
        distance: 200,
        speed: 600,
        animation: 'run',
        invincible: true,
        cooldown: 2000,
        targetType: 'single',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 1 }, frameRate: 3, repeat: -1 },
      { key: 'walk', frames: { start: 25, end: 32 }, frameRate: 6, repeat: -1 },
      { key: 'run', frames: { start: 25, end: 32 }, frameRate: 10, repeat: -1 },
      { key: 'jump', frames: { start: 41, end: 48 }, frameRate: 8, repeat: 0 },
      { key: 'jump_down', frames: { start: 41, end: 48 }, frameRate: 8, repeat: 0 },
      { key: 'attack', frames: { start: 65, end: 68 }, frameRate: 12, repeat: 0 },
    ],
  },
};
