export const CharacterData = {
  monk: {
    sprite: {
      key: 'monk',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        duration: 400,
        animation: 'attack',
        frameRate: 6,
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      attack_2: {
        type: 'melee',
        damage: 15,
        hitbox: { width: 90, height: 40, offsetX: 30, offsetY: 70 },
        duration: 700,
        animation: 'attack_2',
        frameRate: 8,
        knockback: { x: 150, y: -50 },
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      attack_3: {
        type: 'melee',
        damage: 25,
        hitbox: [
          { width: 175, height: 40, offsetX: 80, offsetY: 100 },
          { width: 70, height: 90, offsetX: 130, offsetY: 60 },
        ],
        hitboxDelay: 300,
        duration: 500,
        animation: 'attack_3',
        frameRate: 12,
        knockback: { x: 200, y: -100 },
        effects: ['stun'],
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      air_attack: {
        type: 'melee',
        damage: 20,
        hitbox: { width: 55, height: 50, offsetX: 5, offsetY: 0 },
        hitboxDelay: 100,
        duration: 450,
        animation: 'air_attack',
        frameRate: 12,
        knockback: { x: 120, y: 150 },
        targetType: 'single',
      },
      special_attack: {
        type: 'instant',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        duration: 1500,
        animation: 'special_attack',
        frameRate: 15,
        knockback: { x: 250, y: -150 },
        effects: ['burn'],
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      roll: {
        type: 'movement',
        duration: 400,
        animation: 'roll',
        frameRate: 10,
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      meditate: {
        type: 'buff',
        duration: 2000,
        animation: 'meditate',
        frameRate: 8,
        effects: ['heal', 'mana_regen'],
        healAmount: 20,
        manaAmount: 30,
        cooldown: 10000,
        targetType: 'single',
      },
      fireball: {
        type: 'projectile',
        damage: 30,
        animation: 'special_attack',
        frameRate: 30,
        cooldown: 3000,
        cost: { mana: 15 },
        targetType: 'multi',
      },
      ice_shard: {
        type: 'projectile',
        damage: 20,
        animation: 'special_attack',
        frameRate: 30,
        effects: ['slow'],
        cooldown: 2500,
        cost: { mana: 12 },
        targetType: 'multi',
      },
      lightning: {
        type: 'instant',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        animation: 'special_attack',
        frameRate: 30,
        duration: 1000,
        effects: ['stun'],
        cooldown: 4000,
        cost: { mana: 25 },
        targetType: 'multi',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 5 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 26, end: 31 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 26, end: 31 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 51, end: 52 }, frameRate: 4, repeat: 0 },
      { key: 'jump_down', frames: { start: 76, end: 77 }, frameRate: 4, repeat: 0 },
      { key: 'air_attack', frames: { start: 101, end: 106 }, frameRate: 12, repeat: 0 },
      { key: 'attack', frames: { start: 126, end: 130 }, frameRate: 6, repeat: 0 },
      { key: 'attack_2', frames: { start: 155, end: 161 }, frameRate: 8, repeat: 0 },
      { key: 'attack_3', frames: { start: 187, end: 197 }, frameRate: 12, repeat: 0 },
      { key: 'special_attack', frames: { start: 201, end: 230 }, frameRate: 30, repeat: 0 },
      { key: 'meditate', frames: { start: 226, end: 240 }, frameRate: 8, repeat: -1 },
      { key: 'roll', frames: { start: 251, end: 255 }, frameRate: 10, repeat: 0 },
      { key: 'defend', frames: { start: 276, end: 290 }, frameRate: 15, repeat: -1 },
      { key: 'take_hit', frames: { start: 301, end: 306 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 326, end: 340 }, frameRate: 15, repeat: 0 },
    ],
  },
  assassin: {
    sprite: {
      key: 'assassin',
      frameWidth: 288,
      frameHeight: 128,
      scale: 2.0,
    },
    base: {
      x: 100,
      y: 810,
    },
    physics: {
      collisionBox: { width: 46, height: 76, offsetX: 268, offsetY: 170 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 55, offsetX: 35, offsetY: 70, duration: 400 },
      comboWindow: 450,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 10,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 100 },
        duration: 400,
        animation: 'attack',
        frameRate: 6,
        knockback: { x: 100, y: 0 },
        cooldown: 200,
        targetType: 'multi',
      },
      attack_2: {
        type: 'melee',
        damage: 15,
        hitbox: { width: 90, height: 40, offsetX: 30, offsetY: 70 },
        duration: 700,
        animation: 'attack_2',
        frameRate: 8,
        knockback: { x: 150, y: -50 },
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      attack_3: {
        type: 'instant',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        duration: 500,
        animation: 'attack_3',
        frameRate: 12,
        knockback: { x: 200, y: -100 },
        effects: ['stun'],
        cooldown: 0,
        cost: { mana: 20 },
        targetType: 'multi',
      },
      air_attack: {
        type: 'melee',
        damage: 20,
        hitbox: { width: 55, height: 50, offsetX: 5, offsetY: 0 },
        hitboxDelay: 100,
        duration: 450,
        animation: 'air_attack',
        frameRate: 12,
        knockback: { x: 120, y: 150 },
        targetType: 'single',
      },
      special_attack: {
        type: 'instant',
        hitboxSequence: [
          {
            delay: 100,
            hitbox: { width: 60, height: 40, offsetX: 250, offsetY: 100 },
            damage: 8,
            duration: 800,
            movement: { velocityX: 400, velocityY: 0 },
          },
          {
            delay: 200,
            hitbox: { width: 60, height: 40, offsetX: 50, offsetY: 80 },
            damage: 8,
            duration: 800,
            movement: { velocityX: 400, velocityY: -50 },
          },
          {
            delay: 300,
            hitbox: { width: 60, height: 40, offsetX: -150, offsetY: 120 },
            damage: 8,
            duration: 800,
            movement: { velocityX: 400, velocityY: 50 },
          },
        ],
        animation: 'special_attack',
        frameRate: 20,
        knockback: { x: 150, y: -50 },
        cooldown: 0,
        cost: { mana: 0 },
        targetType: 'multi',
      },
      roll: {
        type: 'movement',
        duration: 400,
        animation: 'roll',
        frameRate: 10,
        invincible: true,
        distance: 150,
        cooldown: 3000,
        targetType: 'single',
      },
      defend: {
        type: 'melee',
        duration: 2000,
        animation: 'defend',
        frameRate: 8,
        effects: ['defend'],
        healAmount: 20,
        manaAmount: 30,
        cooldown: 1000,
        targetType: 'single',
      },
      fireball: {
        type: 'projectile',
        damage: 30,
        animation: 'special_attack',
        frameRate: 30,
        cooldown: 3000,
        cost: { mana: 15 },
        targetType: 'multi',
      },
      ice_shard: {
        type: 'projectile',
        damage: 20,
        animation: 'special_attack',
        frameRate: 30,
        effects: ['slow'],
        cooldown: 2500,
        cost: { mana: 12 },
        targetType: 'multi',
      },
      lightning: {
        type: 'instant',
        hitboxSequence: [
          {
            delay: 0,
            hitbox: { width: 175, height: 40, offsetX: 80, offsetY: 100 },
            damage: 10,
          },
          {
            delay: 200,
            hitbox: { width: 90, height: 90, offsetX: 80, offsetY: 60 },
            damage: 15,
          },
        ],
        animation: 'special_attack',
        frameRate: 30,
        duration: 1000,
        effects: ['stun'],
        cooldown: 4000,
        cost: { mana: 25 },
        targetType: 'multi',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 7 }, frameRate: 8, repeat: -1 },
      { key: 'walk', frames: { start: 30, end: 37 }, frameRate: 8, repeat: -1 },
      { key: 'run', frames: { start: 30, end: 37 }, frameRate: 12, repeat: -1 },
      { key: 'jump', frames: { start: 60, end: 62 }, frameRate: 3, repeat: 0 },
      { key: 'jump_down', frames: { start: 90, end: 92 }, frameRate: 3, repeat: 0 },
      { key: 'air_attack', frames: { start: 120, end: 126 }, frameRate: 12, repeat: 0 },
      { key: 'roll', frames: { start: 150, end: 155 }, frameRate: 10, repeat: 0 },
      { key: 'attack', frames: { start: 180, end: 187 }, frameRate: 12, repeat: 0 },
      { key: 'attack_2', frames: { start: 215, end: 227 }, frameRate: 8, repeat: 0 },
      { key: 'attack_3', frames: { start: 253, end: 265 }, frameRate: 25, repeat: 0 },
      { key: 'special_attack', frames: { start: 270, end: 307 }, frameRate: 37, repeat: 0 },
      { key: 'meditate', frames: { start: 300, end: 307 }, frameRate: 8, repeat: 0 },
      { key: 'defend', frames: { start: 300, end: 307 }, frameRate: 15, repeat: -1 },
      { key: 'take_hit', frames: { start: 330, end: 335 }, frameRate: 8, repeat: 0 },
      { key: 'death', frames: { start: 360, end: 378 }, frameRate: 15, repeat: 0 },
    ],
  },

  soul: {
    sprite: {
      key: 'soul',
      frameWidth: 32,
      frameHeight: 32,
      scale: 2.0,
    },
    base: {
      x: 200,
      y: 600,
    },
    physics: {
      collisionBox: { width: 32, height: 64, offsetX: 16, offsetY: 0 },
      walkSpeed: 200,
      runSpeed: 350,
      jumpPower: 300,
      maxJumps: 2,
    },
    combat: {
      attackHitbox: { width: 50, height: 35, offsetX: 35, offsetY: 0, duration: 400 },
      comboWindow: 400,
    },
    skills: {
      attack: {
        type: 'melee',
        damage: 15,
        hitbox: { width: 50, height: 35, offsetX: 35, offsetY: 0 },
        duration: 400,
        animation: 'attack',
        cooldown: 500,
        frameRate: 12,
        knockback: { x: 100, y: 0 },
        targetType: 'single',
      },
      dash: {
        type: 'movement',
        distance: 200,
        speed: 600,
        duration: 300,
        animation: 'run',
        frameRate: 10,
        invincible: true,
        cooldown: 2000,
        targetType: 'single',
      },
    },
    animations: [
      { key: 'idle', frames: { start: 0, end: 1 }, frameRate: 3, repeat: -1 },
      { key: 'walk', frames: { start: 25, end: 32 }, frameRate: 6, repeat: -1 },
      { key: 'run', frames: { start: 25, end: 32 }, frameRate: 10, repeat: -1 },
      { key: 'jump', frames: { start: 41, end: 48 }, frameRate: 8, repeat: 0 },
      { key: 'jump_down', frames: { start: 41, end: 48 }, frameRate: 8, repeat: 0 },
      { key: 'attack', frames: { start: 65, end: 68 }, frameRate: 12, repeat: 0 },
    ],
  },
};
